### ISSUE TITLE
Support for python2 and python3 as aliases for python

### ISSUE THREAD

**Issue by junichi11** [junichi11/netbeans-noext-mime-resolver#10]

**Comment by junichi11** [comment]
Fixed.

https://github.com/junichi11/netbeans-noext-mime-resolver/releases/tag/v0.8.0

**Comment by mintern** [comment]
That was fast! Thank you!!

**Comment by mintern** [comment]
I can confirm that it worked perfectly for me (for `python3`). Thanks again!

**Comment by junichi11** [comment]
Great to hear. You're welcome :)
