### ISSUE TITLE
Support for the modeline

### ISSUE THREAD

**Issue by diegodiasm** [junichi11/netbeans-noext-mime-resolver#13]
The company I work for has lots of files written in C++ that are saved without extension. They have a convention of naming C libraries with .h and C++ libraries without extension.

Many of the files are annotated with the following metadata on the first line, which I think is a hint for the editor vi to trigger the syntax highlighting.

// vi:set ft=cpp: -*- Mode: C++ -*-
I couldn't find any plugin that automatically detects the programming language on a file. Would you be able to add support in your plugin to this kind of directive?

Thanks

**Comment by junichi11** [comment]
> // vi:set ft=cpp: -_- Mode: C++ -_-

Is there the documentation for that pattern somewhere?

**Comment by diegodiasm** [comment]
This line is a modeline. It tells an editor (e.g. emacs or vi) to choose a specific editing mode for a file. Some information is given in http://vim.wikia.com/wiki/Modeline_magic, but it doesn't provide the syntax in details. Here sare some more examples: http://www.snowfrog.net/2009/01/08/vim-modelines/.

It seems it allows to configure syntax highlighting, tab spacing, etc. There's a plugin for Visual Studio that supports parts of the notation (https://github.com/Microsoft/vscode/issues/1651). The ft tag seems to be the most important. The line might also havr "vim:" instead of vi.

Thanks.

**Comment by diegodiasm** [comment]
Perhaps some additional information about the modeline syntax and its processing may become available on answers to https://stackoverflow.com/questions/52822332/automatic-detection-of-language-for-files-without-extension-in-eclipse-netbeans.

**Comment by diegodiasm** [comment]
Hi @junichi11, it works! 

Netbeans now automatically assigns files to the C++ syntax highlighting after installing the com-junichi11-netbeans-modules-noextresolver-0.8.0.2-dev.nbm. This works if the file already have the modeline on it. 

In the cases that the modeline is not present, I can add it manually and saved the file. In these cases Netbeans only activates the syntax highlighting after closing the IDE and opening the file after restarting it. This is already a very good help. I wonder if it be possible to have a button to request the plugin to reload a file and check if a modeline has been added to it, so it would not be necessary to restart Netbeans.

Thank you very much!
Diego

**Comment by junichi11** [comment]
Great to hear. 

> In the cases that the modeline is not present, I can add it manually and saved the file. In these cases Netbeans only activates the syntax highlighting after closing the IDE and opening the file after restarting it.

Need not to restart it, maybe. Add the modeline then please wait a little while. In my environment, if the file type is changed, the file is reopened automatically.

**Comment by junichi11** [comment]
![nb-noext-resolver](https://user-images.githubusercontent.com/738383/47088786-41f0f480-d25a-11e8-9e5d-ea68edf9f6ca.gif)

**Comment by junichi11** [comment]
If there is a problem, please submit a new issue. Will close this. Thanks.
