### ISSUE TITLE
PHP Support

### ISSUE THREAD

**Issue by Vitexus** [junichi11/netbeans-noext-mime-resolver#16]
Please add support for PHP

**Comment by junichi11** [comment]
Please write details (e.g. an example code).

**Comment by junichi11** [comment]
Fixed: https://github.com/junichi11/netbeans-noext-mime-resolver/releases/tag/v0.12.1
Thanks.

**Comment by junichi11** [comment]
BTW, I've already uploaded the nbm to the Maven Central. But it takes a little time until it is available.

**Comment by Vitexus** [comment]
Thank you very much. Have nice day :)
