### ISSUE TITLE
How do you install it on netbeans 17

### ISSUE THREAD

**Issue by sarelvdm** [junichi11/netbeans-noext-mime-resolver#18]
How do you install it on netbeans 17.
not listed under netbeans plugins or have a .nbm extention

**Comment by junichi11** [comment]
It is available on PP: https://plugins.netbeans.apache.org/catalogue/?id=30
Please don't submit questions to Issues. Instead, please use Discussions: https://github.com/junichi11/netbeans-noext-mime-resolver/discussions
