### ISSUE TITLE
node sebang to js resolver

### ISSUE THREAD

**Issue by pauloch8** [junichi11/netbeans-noext-mime-resolver#4]
Hello!

Node's express framework generates files with 
#!/usr/bin/env node
wrote in javascript.
Could you support this format?

tks

**Comment by junichi11** [comment]
I'll add it.

**Comment by junichi11** [comment]
Done!
Please try to use 0.3.0 : 
https://github.com/junichi11/netbeans-noext-mime-resolver/releases/tag/v0.3.0

**Comment by junichi11** [comment]
@pauloch8 If you have some problems, please feel free to reopen this issue.

**Comment by pauloch8** [comment]
Worked fine!
tks

2015-07-12 11:23 GMT-03:00 junichi11 <notifications@github.com>:

**Comment by junichi11** [comment]
:+1:
