### ISSUE TITLE
support for text/x-perl

### ISSUE THREAD

**Issue by Blobson** [junichi11/netbeans-noext-mime-resolver#6]
It would be nice to support Perl hashbangs.
Awesome plugin BTW.

**Comment by junichi11** [comment]
I'll add it. 

Could you write a shebang line for it? (like this: `#!/usr/bin/env bash`)

Thanks.

**Comment by Blobson** [comment]
I think following two will cover most cases:
   #!/usr/bin/env perl
   #!/usr/bin/perl

Thanks for doing this.

**Comment by junichi11** [comment]
Thanks for it :)

Done.
https://github.com/junichi11/netbeans-noext-mime-resolver/releases/tag/v0.6.0

**Comment by Blobson** [comment]
Awesome, thanks a lot ;)
