### ISSUE TITLE
Add support for groovy

### ISSUE THREAD

**Issue by fonsecas72** [junichi11/netbeans-noext-mime-resolver#7]
`#!/usr/bin/env groovy`
`#!groovy`

**Comment by junichi11** [comment]
I'm sorry to be late. What is the mime type?

**Comment by fonsecas72** [comment]
`text/x-groovy`

**Comment by junichi11** [comment]
Thanks!

**Comment by junichi11** [comment]
Fixed.
https://github.com/junichi11/netbeans-noext-mime-resolver/releases/tag/v0.7.0

Thanks.

**Comment by fonsecas72** [comment]
Great! Thanks!
