### ISSUE TITLE
No resolving, after choose "Open file as..."

### ISSUE THREAD

**Issue by Chris2011** [junichi11/netbeans-noext-mime-resolver#8]
Based on this ticket: https://github.com/junichi11/netbeans-noext-mime-resolver/issues/4 the problem is there is a www file inside the project and it should resolved by your plugin, but I choose the "Open File As..." option on right click for this file and now it has a different mimetype. And each file, without an extension. has the same mimetype.

It is not possible anymore, that your plugin can handle the shebang url in this file and resolve the file to the correct mimetype, which is: `#!/usr/bin/env node` -> text/javascript.

So is it possible to make a higher priority, that your plugin always jumps in? I use 0.7.0 of your plugin and NetBeans 8.2.

Regards

Chris

**Comment by junichi11** [comment]
I think that it is correct behavior because you choose the "Open File As" option intentionally.

**Comment by Chris2011** [comment]
Yeah I think so too, but it was more or less accidentally. So I think it should always be possible that your plugin sets the mimetype, if there is a shebang AND there is no plugin, which handles. Or I have to find the association to delete it, so that your plugin can jump in.

**Comment by junichi11** [comment]
Probably, it is not possible. I think that default features should take priority because usually user chooses it intentionally as I wrote above.

**Comment by Chris2011** [comment]
Pity but ok, thx.
