### ISSUE TITLE
Resolver should resolve file after adding shebang url and save

### ISSUE THREAD

**Issue by Chris2011** [junichi11/netbeans-noext-mime-resolver#9]
Atm, I can create a new file without an extension and your plugin will not resolves it, when I add the shebang comment `#!/usr/bin/env node`. I closed the file, reopened it, refresh the folder, nothing worked. Only NetBeans restart. Please add the functionality, that the plugin resolves the mimetype, after adding the shebang comment AND saving the file.

Regards

Chris

**Comment by Chris2011** [comment]
WebStorm handles it after saving, Visual Studio Code handles it after reopening the file.

**Comment by Chris2011** [comment]
I prefer the WebStorm handling. And this should be possible I think.

**Comment by junichi11** [comment]
Unfortunately, we cannot this problem. I have no idea at the moment. Probably, FileObject(mimetype) is cached but I'm not sure whether it is possible to clear in the plugin.

This problem also occurs with another case. e.g.
1. Create an empty file without ext (test)
2. Write the following code
```php
<?php
echo "test";
```
3. No syntax highlighting
4. Restart IDE
5. Syntax highlighting for PHP is available
6. Remove text and reopen the file
7. The file is recognized as PHP still
8. Restart IDE
9. The file is not recognized as PHP

**Comment by Chris2011** [comment]
The case with the PHP, will be not handled from your plugin, right? What come into my mind, what your plugin can try is to get the editor from the file and do a setContentType. I think after this, it will reload the file/editor. Before you have to temporarely save the text and the cursor position, but this is simple. And while saving the file, your plugin comes in. It comes in, when the IDE starts and it should comes in, when you change text inside the file.

**Comment by junichi11** [comment]
Improved. Please try to use 0.7.0.1-dev : https://github.com/junichi11/netbeans-noext-mime-resolver/releases/tag/v0.7.0

If a shebang line is changed on save, the file is reopened after one second.
I don't want to publish a new version soon because there may be some problems.

**Comment by Chris2011** [comment]
Great, works like a charme 👍 Thx.

**Comment by Chris2011** [comment]
I will come back if I have problems.

**Comment by junichi11** [comment]
OK :)
